spring.application.name=compraventas
server.port=8082
spring.data.mongodb.uri=mongodb+srv://angelsaez:sjsfLQLTrpKkFPtB@arso-cluster.ins4vie.mongodb.net/compraventas?appName=arso-cluster
microservicio.productos.url=http://localhost:8081/
microservicio.usuarios.url=http://localhost:8080/api/
spring.rabbitmq.uri=amqps://mjxnthmp:pq0QmuFwei2ZNuHoSh2F8dtuQZxZl6co@rat.rmq2.cloudamqp.com/mjxnthmp