spring.application.name=compraventas
server.port=8082
spring.data.mongodb.uri=mongodb://mongodb:27017/compraventas
microservicio.productos.url=http://productos:8081/
microservicio.usuarios.url=http://usuarios:8080/api/
spring.rabbitmq.addresses=amqp://guest:guest@rabbitmq:5672