spring.application.name=pasarela
server.port=8090

# ===== URLs de los microservicios =====
microservicio.usuarios.url=http://usuarios:8080/api/
microservicio.productos.url=http://productos:8081/api/
microservicio.compraventas.url=http://compraventas:8082/api/

# ===== Enrutamiento Zuul =====
zuul.sensitiveHeaders=
zuul.ignored-patterns=/auth/**

zuul.routes.usuarios.path=/api/usuarios/**
zuul.routes.usuarios.url=http://usuarios:8080/api/usuarios/

zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://productos:8081/api/productos/

zuul.routes.compraventas.path=/compraventas/**
zuul.routes.compraventas.url=http://compraventas:8082/api/compraventas/

# ===== OAuth2 GitHub =====
spring.security.oauth2.client.registration.github.clientId=Ov23liUbklO4TODHmBEe
spring.security.oauth2.client.registration.github.clientSecret=e641b2dc4db42977af02a44ada0daca981477b4f
spring.security.oauth2.client.registration.github.scope=user:email,read:user