spring.application.name=productos
server.port=8081
spring.datasource.url=jdbc:mysql://mysql:3306/productos?serverTimezone=CET&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=practicas
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.rabbitmq.addresses=amqp://guest:guest@rabbitmq:5672