segundum.modelo.Usuario=segundum.repositorio.RepositorioUsuariosAdHocJPA
segundum.modelo.Categoria=segundum.repositorio.RepositorioCategoriasAdHocJPA
segundum.modelo.Producto=segundum.repositorio.RepositorioProductosAdHocJPA
