segundum.productos.modelo.Usuario=segundum.productos.repositorio.RepositorioUsuariosAdHocJPA
segundum.productos.modelo.Categoria=segundum.productos.repositorio.RepositorioCategoriasAdHocJPA
segundum.productos.modelo.Producto=segundum.productos.repositorio.RepositorioProductosAdHocJPA
